quarkus:
  application:
    name: ms-transaction
  smallrye-health:
    root-path: /health
    ui:
      enabled: false
  http:
    root-path: /ms-transaction
    port: 18080

info:
  project:
    artifact: ${project.artifactId}
    version: ${project.version}